FROM eclipse-temurin:21-jre
LABEL org.opencontainers.image.source="https://github.com/nilenso/ashutosh-onboarding"
COPY target/uberjar/clinic-latest-standalone.jar /app.jar
CMD ["java", "-jar", "/app.jar"]
