name: Clinic
on:
  push:
    branches:
      - main
    tags:
      - "**"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main

env:
  JDK_DISTRIBUTION: temurin
  JAVA_VERSION: 17

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      hapi-fhir:
        image: hapiproject/hapi:latest
        env:
          server.port: 8090
          hapi.fhir.tester.home.server_address: http://localhost:8090/fhir
          hapi.fhir.allow_multiple_delete: true
        ports:
          - 8090:8090
    defaults:
      run:
        working-directory: ./clinic
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      # can't use `services.[id].options` to add Docker health checks because
      # HAPI has a scratch docker image without a shell installation.
      - name: HAPI FHIR Health Check
        run: while ! curl -sSI "http://localhost:8090"; do sleep 5; done
      - name: Run Tests
        run: lein test
